### PR TITLE
boards: add test cases for the Kontron pitx-imx8m board

### PR DESCRIPTION
**Pull request by hthiery**
Signed-off-by: Heiko Thiery <heiko.thiery@gmail.com>

### CODE REVIEW

**Comment by gctucker** [comment]
Sorry for the slow review.  This looks fine, we just need to create a new buildroot image with the bootrr changes to test it on staging.  It should get resolved this week before the production update next Monday.

**Review by gctucker — APPROVED** [review]
Tested OK on staging:
https://staging.kernelci.org/test/plan/id/61669c361fe4ddcc26a6c425/

There was just one failure:
https://staging.kernelci.org/test/case/id/61669c361fe4ddcc26a6c439/

Is this expected?

**Comment by hthiery** [comment]
> There was just one failure: https://staging.kernelci.org/test/case/id/61669c361fe4ddcc26a6c439/
> 
> Is this expected?

No this is not expected ... I will check that and come back

**Comment by hthiery** [comment]
Hi @gctucker, I solved the problem. It was HW related (the network controller was not flashed). So now it should work.

**Comment by gctucker** [comment]
OK great it's all green now:
https://staging.kernelci.org/test/plan/id/616cc6a57dcf4091dfa6c443/

**Pull request merged**
