### PR TITLE
boards: add test cases for Kontron sl28 boards

### PR DESCRIPTION
**Pull request by mwalle**
Add basic test scripts for the Kontron sl28 boards and its variants.

Signed-off-by: Michael Walle <michael@walle.cc>

### CODE REVIEW

**Comment by gctucker** [comment]
LGTM, this will get tested on staging, I'll put a comment when we get some results.

**Comment by mwalle** [comment]
Thanks. btw some pcie tests are expected to fail due to
https://lore.kernel.org/lkml/4b9ae679b6f76d2f7e340e2ec229dd53@walle.cc/

**Comment by gctucker** [comment]
These files were not being installed because they're not listed in the `Makefile`.  I've made a PR to automatically install all the scripts in `boards/*` and `helpers/*` to avoid hitting this issue again (it's not the first time...) - see #10.

**Comment by gctucker** [comment]
Some results are in: https://staging.kernelci.org/test/plan/id/6053aeba840981669d7ca9f2/

**Comment by gctucker** [comment]
More results with mainline:
https://staging.kernelci.org/test/plan/id/6053cfce939342f2467cab10/
https://staging.kernelci.org/test/plan/id/6053d124090ad9cc587caa57/
https://staging.kernelci.org/test/plan/id/6053cf4249b9e4a7f17ca9f6/
https://staging.kernelci.org/test/plan/id/6053d122090ad9cc587ca9f1/

**Comment by gctucker** [comment]
Tested OK on staging with the rootfs built using the staging.kernelci.org branch:
https://storage.kernelci.org/images/rootfs/buildroot/staging-20210318.0/

**Review by gctucker — APPROVED** [review]

**Pull request merged**
