### PR TITLE
board: add support for kontron n801x-s

### PR DESCRIPTION
**Pull request by hthiery**
Signed-off-by: Heiko Thiery <heiko.thiery@gmail.com>

### CODE REVIEW

**Comment by gctucker** [comment]
The `imx8mm-n801x-s` device is not in `test-configs.yaml`.  Is it in Kontron's lab and has the device type been upstreamed in LAVA?

**Comment by hthiery** [comment]
> The `imx8mm-n801x-s` device is not in `test-configs.yaml`. Is it in Kontron's lab and has the device type been upstreamed in LAVA?

No, unfortunately the board is not yet in our lab. I had made this PR with the assumption that we would get the hardware quickly. Unfortunately this is delayed.

**Comment by gctucker** [comment]
OK, well at least we have a buildroot image with the tests ready to be used for when the device type becomes available.

**Comment by gctucker** [comment]
@hthiery Hello, I see the device is still not in the Kontron lab and it's not in `test-configs.yaml` either. So I think we should close this PR, and if you want to add some tests to be run elsewhere then maybe submit them in the upstream repo rather than the KernelCI fork. What do you reckon?

**Comment by hthiery** [comment]
@gctucker what do you mean with "submit them in the upstream repo"? Nevertheless I've got the information about the board that it will be sent to us in the next days. That means we should be able to bring that board in our lavalab setup very soon.

**Comment by gctucker** [comment]
> @gctucker what do you mean with "submit them in the upstream repo"?

This is the upstream bootrr: https://github.com/andersson/bootrr

Adding something only to the KernelCI fork is useful for tests to run in KernelCI.

> Nevertheless I've got the information about the board that it will be sent to us in the next days. That means we should be able to bring that board in our lavalab setup very soon.

Ah good :)

**Comment by hthiery** [comment]
Ah ok I understand.

It's a real coincidence that you're asking again today. I got the message exactly this morning that we are getting the board for our Lavalab ;-)

**Comment by hthiery** [comment]
@gctucker I can happily tell you that today we integrated the board into our lavalab

**Comment by gctucker** [comment]
> @gctucker I can happily tell you that today we integrated the board into our lavalab

Fantastic news!  And I see it's being enabled in `test-configs.yaml` too: https://github.com/kernelci/kernelci-core/pull/1072

Results are looking good on staging:
https://staging.kernelci.org/test/plan/id/6229b738fff1d46a084b312e/

**Comment by gctucker** [comment]
However, the tests above were run with this rootfs image:
http://storage.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20220228.1/arm64/rootfs.cpio.gz

which in principle should not have the changes from this PR since it's not merged yet :thinking: 

I'll extract it and check what's going on there.

**Comment by gctucker** [comment]
Sorry, wrong board. I was looking at `kontron-pitx-imx8m`.

**Comment by gctucker** [comment]
Building new buildroot images on staging now to test with these extra scripts.

**Review by gctucker — APPROVED** [review]
Tested OK on staging:
https://staging.kernelci.org/test/plan/id/623aa605c0bbfaefcefb0c9f/

**Pull request merged**
